'use client';
import { ChangeEvent, DragEvent, FormEvent, useRef, useState } from 'react';
import React from 'react';

export default function UploadZone({ onUpload }: { onUpload: (file: File) => Promise<void> }) {
  const [file, setFile] = useState<File | null>(null); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const input = useRef<HTMLInputElement>(null);
  const choose = (candidate: File) => { if (candidate.type !== 'application/pdf' && !candidate.name.toLowerCase().endsWith('.pdf')) { setError('Please choose a PDF report.'); return; } if (candidate.size > 20 * 1024 * 1024) { setError('This report is larger than the 20 MB limit.'); return; } setError(''); setFile(candidate); };
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file) return; setBusy(true); try { await onUpload(file); } catch { /* parent presents the safe user-facing error */ } finally { setBusy(false); } };
  const drop = (event: DragEvent<HTMLDivElement>) => { event.preventDefault(); const dropped = event.dataTransfer.files[0]; if (dropped) choose(dropped); };
  return <form onSubmit={submit}><div onDragOver={e => e.preventDefault()} onDrop={drop} className="rounded-2xl border-2 border-dashed border-[#b8c9dc] bg-white p-12 text-center shadow-sm"><div className="mx-auto max-w-xl"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-[#e8f5f3] text-xl text-teal">↑</div><h3 className="mt-4 text-lg font-bold">Drag & drop your PDF here</h3><p className="mt-1 text-sm text-slate-500">or choose a report from your device</p><input aria-label="PDF file" ref={input} className="hidden" type="file" accept="application/pdf,.pdf" onChange={(e: ChangeEvent<HTMLInputElement>) => e.target.files?.[0] && choose(e.target.files[0])} /><button type="button" onClick={() => input.current?.click()} className="focus-ring mt-6 rounded-lg bg-ink px-5 py-3 text-sm font-bold text-white">Browse PDF</button>{file && <p className="mt-5 text-sm font-semibold text-teal">{file.name} · {(file.size / 1024 / 1024).toFixed(2)} MB</p>}<p className="mt-6 text-xs text-slate-500">Supported: PDF · Maximum: 20 MB</p><p className="mt-3 text-xs text-slate-500">Reports are processed locally by the configured document processing services. No external AI or OCR service is required.</p></div></div>{error && <p role="alert" className="mt-4 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{file && <button disabled={busy} className="focus-ring mt-5 w-full rounded-lg bg-teal px-5 py-3 font-bold text-white disabled:opacity-60">{busy ? 'Reading document and extracting results…' : 'Process report'}</button>}</form>;
}
